### ISSUE TITLE
User story acceptance Criteria - As an Administrator I want to add employees so that I can later track their vacation time.

### ISSUE THREAD

**Issue by ErinClaudio** [ErinClaudio/stunning-robot-HR#2]

**Comment by rbeaver555** [comment]
The system will allow me to add an employee with the following fields:
1. Fullname
2. Date of Birth
3. Position
4. Start Date

The system will allow me to update an employee.
The system will allow me to remove an employee.
The system will show all active employees.

**Comment by ErinClaudio** [comment]
@rbeaver555 I have a couple of questions for you about this Issue. When you have a moment
